### ISSUE TITLE
Downloading your code and trying it for India and Asia

### ISSUE THREAD

**Issue by winash12** [guidocioni/icon_forecasts#1]
@guidocioni I am planning to download your code and try to plot ICON data for the Indian subcontinent. Hope to succeed !

https://askubuntu.com/questions/12764/where-do-i-get-a-package-for-gnu-parallel I am doing this on Ubuntu so I need to install GNU Parallel as well I think.

**Comment by guidocioni** [comment]
you may want to have a look at the repository of icon global, this version only covers Europe

**Comment by winash12** [comment]
@guidocioni Thanks for the prompt response.  Wouldn't ICON Europe be better - all I have to do is replace the EU lat lon box with Asia ? I do not want to download ICON data for the whole world.

**Comment by guidocioni** [comment]
as the name suggests, ICON Europe has data only over Europe: you can't plot anything outside of that region.
I'd suggest you to take a look at the documentation of the models before trying to use this package

**Comment by winash12** [comment]
@guidocioni Apologies. I have not looked at your code I have not downloaded ICON data before. I have gotten data officially from DWD but never downloaded and they do the subset and send it to me .I run COSMO which is a mesoscale model  I have downloaded ERA5 and NCAR reanalysis. In both you specify latlon box which defines the area you want to subset. That is why I asked if your download file takes lat lon as input.

**Comment by guidocioni** [comment]
You can do exactly the same but you'd have to use the icon global repository. 
And unfortunately there's no tool to subset the data on the server side as they are bzip2 grib files: you have to download the data and process it yourself.
Still it is not too complicated because the pipeline uses some parallelized funcions that make use of cdo to do some preprocessing steps on the data, so you can just add your setlonlatbox call.

I'll close for now as this is not relevant and not an issue of this repo but feel free to ask more general questions in the discussion section.
